basic functionality for Intel-MPI on CPUs. Left support for OpenMPI although not currently available on Derecho

diff --git a/balanced b/balanced
--- a/balanced
+++ b/balanced
@@ -8,14 +8,20 @@ elif [ $LMOD_FAMILY_MPI == "openmpi" ]; then
   grank=$OMPI_COMM_WORLD_RANK
   lrank=$OMPI_COMM_WORLD_LOCAL_RANK
   lsize=$OMPI_COMM_WORLD_LOCAL_SIZE
+elif [ $LMOD_FAMILY_MPI == "intel-mpi" ]; then
+  grank=$PMI_RANK
+  lrank=$MPI_LOCALRANKID
+  lsize=$MPI_LOCALNRANKS
 else
-  >&2 echo "Error: mpibind balanced requires either cray-mpich or openmpi"
+  >&2 echo "Error: mpibind balanced requires either cray-mpich or intel-mpi"
   exit 2
 fi
 
 if [[ -z "$OMP_NUM_THREADS" ]]; then 
   export OMP_NUM_THREADS=1
 fi
+export OMP_PLACES=threads 
+export OMP_PROC_BIND=close 
 nthds=$OMP_NUM_THREADS
 nsock=`lscpu | grep Socket | awk '{print $2}'`
 cpsock=`lscpu | grep "per sock" | awk '{print $4}'`
diff --git a/mpibind b/mpibind
--- a/mpibind
+++ b/mpibind
@@ -1,22 +1,24 @@
 #!/bin/bash
 parse_chunk () {
-        chunk=$1
+   chunk=$1
 	nodes_in_chunk=`echo $chunk | sed "s/^\([0-9]\+\).*/\1/"`
-        mpi_per_node=`echo $chunk | sed "s/.*mpiprocs=\([0-9]\+\).*/\1/"`
+   mpi_per_node=`echo $chunk | sed "s/.*mpiprocs=\([0-9]\+\).*/\1/"`
 	if [[ $(echo $chunk | grep ompthreads) ]]; then
 	   omp_per_node=`echo $chunk | sed "s/.*ompthreads=\([0-9]\+\).*/\1/"`
 	else
 	   omp_per_node=1
-        fi
+   fi
 	tot_mpi=$((nodes_in_chunk*mpi_per_node))
 	if [ $LMOD_FAMILY_MPI == "cray-mpich" ]; then
-           printf "%s" "-n $tot_mpi -ppn $mpi_per_node --cpu-bind none -env OMP_NUM_THREADS=$omp_per_node "
-        elif [ $LMOD_FAMILY_MPI == "openmpi" ]; then
-           printf "%s" "-np $tot_mpi --map-by ppr:$mpi_per_node:node --bind-to none --oversubscribe -x OMP_NUM_THREADS=$omp_per_node -x TMPDIR "
-        else
-           >&2 echo "Error: mpibind requires either cray-mpich or openmpi"
-           exit 1
-        fi
+      printf "%s" "-n $tot_mpi -ppn $mpi_per_node --cpu-bind none -env OMP_NUM_THREADS=$omp_per_node "
+   elif [ $LMOD_FAMILY_MPI == "openmpi" ]; then
+      printf "%s" "-np $tot_mpi --map-by ppr:$mpi_per_node:node --bind-to none --oversubscribe -x OMP_NUM_THREADS=$omp_per_node -x TMPDIR "
+   elif [ $LMOD_FAMILY_MPI == "intel-mpi" ]; then
+      printf "%s" "-n $tot_mpi -ppn $mpi_per_node -genvall -genv I_MPI_PIN=no -genv OMP_NUM_THREADS=$omp_per_node "      
+   else
+      >&2 echo "Error: mpibind requires either cray-mpich or intel-mpi"
+      exit 1
+   fi
 }
 
 args=$*
@@ -30,10 +32,10 @@ for c in $chunks; do
    mpicmd+="$args : "
 done
 mpicmd=`echo "$mpicmd" | sed "s/: $//"`
-echo "-- -- -- --" >> mpibind.log
-echo "MPI exec line:" >> mpibind.log
-echo "  $mpicmd" >> mpibind.log
-echo "-- -- -- --" >> mpibind.log
+echo "-- -- -- --"     >> mpibind.log
+echo "MPI exec line:"  >> mpibind.log
+echo "  $mpicmd"       >> mpibind.log
+echo "-- -- -- --"     >> mpibind.log
 echo "Binding Report:" >> mpibind.log
 $mpicmd
 cat $TMPDIR/mpibind.log.*.tmp | sort -g -k 2 >> mpibind.log
