Updated error messages for unsupported MPIs

diff --git a/cpu_bind b/cpu_bind
--- a/cpu_bind
+++ b/cpu_bind
@@ -13,7 +13,7 @@ elif [ $LMOD_FAMILY_MPI == "intel-mpi" ]; then
   lrank=$MPI_LOCALRANKID
   lsize=$MPI_LOCALNRANKS
 else
-  >&2 echo "Error: mpibind balanced requires either cray-mpich or intel-mpi"
+  >&2 echo "Error: mpibind requires either cray-mpich or intel-mpi for binding CPU applications"
   exit 2
 fi
 
diff --git a/gpu_bind b/gpu_bind
--- a/gpu_bind
+++ b/gpu_bind
@@ -10,7 +10,7 @@ elif [ $LMOD_FAMILY_MPI == "openmpi" ]; then
   lrank=$OMPI_COMM_WORLD_LOCAL_RANK
   lsize=$OMPI_COMM_WORLD_LOCAL_SIZE
 else
-  >&2 echo "Error: mpibind gpu_per_rank requires cray-mpich"
+  >&2 echo "Error: mpibind requires cray-mpich for binding GPU applications"
   exit 2
 fi
 
